[package]
name = "mac128k_emulator"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc = "1.0"
reqwest = { version = "0.11", features = ["blocking"] }
zip = "0.6"
bindgen = "0.71.1"

[dependencies]
winit = "0.28"
pixels = "0.12"
log = "0.4"
env_logger = "0.11"
